module Mangadex
open FSharp.Data
open System.IO

// JSON Schemas
// Generated by: https://jsoncrack.com/editor

// API Endpoint
// Provides images from a valid chapter identifier
// https://api.mangadex.org/at-home/server/${chapterId}

[<Literal>]
let private MANGADEX_IMAGES_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "result": {
      "type": "string"
    },
    "baseUrl": {
      "type": "string"
    },
    "chapter": {
      "type": "object",
      "properties": {
        "hash": {
          "type": "string"
        },
        "data": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dataSaver": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "hash",
        "data",
        "dataSaver"
      ]
    }
  },
  "required": [
    "result",
    "baseUrl",
    "chapter"
  ]
}
"""

// API Endpoint
// Provides chapter identifiers from a valid manga identifier
// ExternalUrl(?) is disabled by default
// Language(?) is set to English by default
// Chapter(?) is an array of integers
// https://api.mangadex.org/chapter?includeExternalUrl=0&translatedLanguage[]=en&manga=${mangaId}&chapter[]=1&chapter[]=2

[<Literal>]
let private MANGDADEX_CHAPTERS_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "result": {
      "type": "string"
    },
    "response": {
      "type": "string"
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "properties": {
              "volume": {
                "type": "string"
              },
              "chapter": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "translatedLanguage": {
                "type": "string"
              },
              "externalUrl": {},
              "publishAt": {
                "type": "string"
              },
              "readableAt": {
                "type": "string"
              },
              "createdAt": {
                "type": "string"
              },
              "updatedAt": {
                "type": "string"
              },
              "pages": {
                "type": "number"
              },
              "version": {
                "type": "number"
              }
            },
            "required": [
              "volume",
              "chapter",
              "title",
              "translatedLanguage",
              "externalUrl",
              "publishAt",
              "readableAt",
              "createdAt",
              "updatedAt",
              "pages",
              "version"
            ]
          },
          "relationships": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "type"
              ]
            }
          }
        },
        "required": [
          "id",
          "type",
          "attributes",
          "relationships"
        ]
      }
    },
    "limit": {
      "type": "number"
    },
    "offset": {
      "type": "number"
    },
    "total": {
      "type": "number"
    }
  },
  "required": [
    "result",
    "response",
    "data",
    "limit",
    "offset",
    "total"
  ]
}
""" 

[<Literal>]
let private MANGADEX_FEED_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "result": {
      "type": "string"
    },
    "response": {
      "type": "string"
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "properties": {
              "volume": {
                "type": "string"
              },
              "chapter": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "translatedLanguage": {
                "type": "string"
              },
              "externalUrl": {},
              "publishAt": {
                "type": "string"
              },
              "readableAt": {
                "type": "string"
              },
              "createdAt": {
                "type": "string"
              },
              "updatedAt": {
                "type": "string"
              },
              "pages": {
                "type": "number"
              },
              "version": {
                "type": "number"
              }
            },
            "required": [
              "chapter",
              "title",
              "translatedLanguage",
              "externalUrl",
              "publishAt",
              "readableAt",
              "createdAt",
              "updatedAt",
              "pages",
              "version"
            ]
          },
          "relationships": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "type"
              ]
            }
          }
        },
        "required": [
          "id",
          "type",
          "attributes",
          "relationships"
        ]
      }
    },
    "limit": {
      "type": "number"
    },
    "offset": {
      "type": "number"
    },
    "total": {
      "type": "number"
    }
  },
  "required": [
    "result",
    "response",
    "data",
    "limit",
    "offset",
    "total"
  ]
}
"""

type MangadexImages = JsonProvider<Schema=MANGADEX_IMAGES_SCHEMA>
type MangadexChapters = JsonProvider<Schema=MANGDADEX_CHAPTERS_SCHEMA>
type MangadexFeed = JsonProvider<Schema=MANGADEX_FEED_SCHEMA>

[<Literal>]
let private API = "https://api.mangadex.org"

[<Literal>]
let IMAGE_ENDPOINT = API + "/at-home/server"

[<Literal>]
let MANGA_ENDPOINT = API + "/chapter?includeExternalUrl=0&translatedLanguage[]=en"

[<Literal>]
let FEED_ENDPOINT = API + "/manga/{0}/feed?limit={1}&includeExternalUrl=0&translatedLanguage[]=en&order[chapter]=asc"

[<Literal>]
let FEED_BATCHSIZE = 500
