module Mangadex

open FSharp.Data

// ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
// ┃ JSON Schemas                               ┃
// ┃ Generated by: https://jsoncrack.com/editor ┃
// ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

// Provides images of a chapter
// https://api.mangadex.org/at-home/server/${chapterId}

[<Literal>]
let private MANGADEX_IMAGES_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "result": {
      "type": "string"
    },
    "baseUrl": {
      "type": "string"
    },
    "chapter": {
      "type": "object",
      "properties": {
        "hash": {
          "type": "string"
        },
        "data": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dataSaver": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "hash",
        "data",
        "dataSaver"
      ]
    }
  },
  "required": [
    "result",
    "baseUrl",
    "chapter"
  ]
}
"""

// Provides all available chapters in a paginated manner
// https://api.mangadex.org/manga/${titleId}/feed

[<Literal>]
let private MANGADEX_FEED_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "result": {
      "type": "string"
    },
    "response": {
      "type": "string"
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "properties": {
              "volume": {
                "type": "string"
              },
              "chapter": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "translatedLanguage": {
                "type": "string"
              },
              "externalUrl": {},
              "publishAt": {
                "type": "string"
              },
              "readableAt": {
                "type": "string"
              },
              "createdAt": {
                "type": "string"
              },
              "updatedAt": {
                "type": "string"
              },
              "pages": {
                "type": "number"
              },
              "version": {
                "type": "number"
              }
            },
            "required": [
              "chapter",
              "title",
              "translatedLanguage",
              "externalUrl",
              "publishAt",
              "readableAt",
              "createdAt",
              "updatedAt",
              "pages",
              "version"
            ]
          },
          "relationships": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "type"
              ]
            }
          }
        },
        "required": [
          "id",
          "type",
          "attributes",
          "relationships"
        ]
      }
    },
    "limit": {
      "type": "number"
    },
    "offset": {
      "type": "number"
    },
    "total": {
      "type": "number"
    }
  },
  "required": [
    "result",
    "response",
    "data",
    "limit",
    "offset",
    "total"
  ]
}
"""

// Provides info on a specific chapter
// https://api.mangadex.org/chapter/${chapterId}

[<Literal>]
let private MANGADEX_CHAPTER_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "result": {
      "type": "string"
    },
    "response": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "attributes": {
          "type": "object",
          "properties": {
            "volume": {
              "type": "string"
            },
            "chapter": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "translatedLanguage": {
              "type": "string"
            },
            "externalUrl": {},
            "isUnavailable": {
              "type": "boolean"
            },
            "publishAt": {
              "type": "string"
            },
            "readableAt": {
              "type": "string"
            },
            "createdAt": {
              "type": "string"
            },
            "updatedAt": {
              "type": "string"
            },
            "pages": {
              "type": "number"
            },
            "version": {
              "type": "number"
            }
          },
          "required": [
            "volume",
            "chapter",
            "title",
            "translatedLanguage",
            "externalUrl",
            "isUnavailable",
            "publishAt",
            "readableAt",
            "createdAt",
            "updatedAt",
            "pages",
            "version"
          ]
        },
        "relationships": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "type"
            ]
          }
        }
      },
      "required": [
        "id",
        "type",
        "attributes",
        "relationships"
      ]
    }
  },
  "required": [
    "result",
    "response",
    "data"
  ]
}
"""

// Provides info on scanlator groups
// https://api.mangadex.org/group/${scanlatorId}

[<Literal>]
let private MANGADEX_SCANLATOR_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "result": {
      "type": "string"
    },
    "response": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "attributes": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "altNames": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "en": {
                    "type": "string"
                  }
                },
                "required": [
                  "en"
                ]
              }
            },
            "locked": {
              "type": "boolean"
            },
            "website": {
              "type": "string"
            },
            "ircServer": {},
            "ircChannel": {},
            "discord": {},
            "contactEmail": {},
            "description": {
              "type": "string"
            },
            "twitter": {},
            "mangaUpdates": {
              "type": "string"
            },
            "focusedLanguages": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "official": {
              "type": "boolean"
            },
            "verified": {
              "type": "boolean"
            },
            "inactive": {
              "type": "boolean"
            },
            "publishDelay": {},
            "createdAt": {
              "type": "string"
            },
            "updatedAt": {
              "type": "string"
            },
            "version": {
              "type": "number"
            }
          },
          "required": [
            "name",
            "altNames",
            "locked",
            "website",
            "ircServer",
            "ircChannel",
            "discord",
            "contactEmail",
            "description",
            "twitter",
            "mangaUpdates",
            "focusedLanguages",
            "official",
            "verified",
            "inactive",
            "publishDelay",
            "createdAt",
            "updatedAt",
            "version"
          ]
        },
        "relationships": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "type"
            ]
          }
        }
      },
      "required": [
        "id",
        "type",
        "attributes",
        "relationships"
      ]
    }
  },
  "required": [
    "result",
    "response",
    "data"
  ]
}
"""

type MangadexImages = JsonProvider<Schema=MANGADEX_IMAGES_SCHEMA>
type MangadexFeed = JsonProvider<Schema=MANGADEX_FEED_SCHEMA>
type MangadexChapter = JsonProvider<Schema=MANGADEX_CHAPTER_SCHEMA>
type MangadexScanlator = JsonProvider<Schema=MANGADEX_SCANLATOR_SCHEMA>

[<Literal>]
let private API = "https://api.mangadex.org"

[<Literal>]
let IMAGE_ENDPOINT = API + "/at-home/server/{0}"

[<Literal>]
let FEED_ENDPOINT = API + "/manga/{0}/feed?limit={1}&includeExternalUrl=0&translatedLanguage[]=en&order[chapter]=asc"

[<Literal>]
let FEED_BATCHSIZE = 500

[<Literal>]
let CHAPTER_ENDPOINT = API + "/chapter/{0}"

[<Literal>]
let SCANLATOR_ENDPOINT = API + "/group/{0}"
